---
# tasks file for docker
- name: Include variables based on OS Family 
  include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Include tasks based on OS Family 
  include_tasks: "docker-{{ ansible_facts['os_family'] }}.yml"